name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Sync local repo
        working-directory: /home/vanep/vanep-projects/vanep-mobile
        run: |
          git pull origin main
          echo "Repo local sincronizado!"
